### ISSUE TITLE
Request for license documentation

### ISSUE THREAD

**Issue by bakerkj** [kierdavis/dateparser#2]
To be able to reuse this code it would be useful if the license terms of the code were documented.  Given that this is a translation of the Python dateutil.parserport of the python-dateutil package I'd suggest using a similar license (Simplified BSD).

Thanks!

**Comment by kierdavis** [comment]
Thank you for bringing this to my attention. I don't really use or maintain this code anymore, but let me know if you have any problems using this and I'll see what I can do to help.

**Comment by bakerkj** [comment]
> Thank you for bringing this to my attention. I don't really use or maintain this
> code anymore, but let me know if you have any problems using this and I'll see what
> I can do to help.

Thanks for specifying the license.  I appreciate it.  If I find any issues I'll let
you know.  Thanks...

-- Ken
